"use client";
import { useEffect, useState } from "react";

// Circle Arc App Kit panel — configurable capabilities per dapp group.
// caps subset of: "balance" | "deposit" | "send" | "swap" | "bridge" | "earn"
const fmt = (a: string) => `${a.slice(0, 6)}…${a.slice(-4)}`;
const ARC_HEX = "0x4cef52";
const ARC_PARAMS = { chainId: ARC_HEX, chainName: "Arc Testnet", nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: ["https://rpc.testnet.arc.network"], blockExplorerUrls: ["https://testnet.arcscan.app"] };
function getProvider() { const w = window as any; let p = w.okxwallet || w.ethereum; if (w.ethereum?.providers?.length) p = w.ethereum.providers.find((x: any) => x.isMetaMask) || w.ethereum.providers[0]; return p; }
async function ensureArc(p: any) { try { await p.request({ method: "wallet_switchEthereumChain", params: [{ chainId: ARC_HEX }] }); } catch (e: any) { if (e?.code === 4902 || e?.code === -32603) await p.request({ method: "wallet_addEthereumChain", params: [ARC_PARAMS] }); } }
async function adapterOf(p: any) { const { createViemAdapterFromProvider } = await import("@circle-fin/adapter-viem-v2"); return await createViemAdapterFromProvider({ provider: p } as any); }

type Cap = "balance" | "deposit" | "send" | "swap" | "bridge" | "earn";
export function AppKitPanel({ color = "emerald", caps = ["balance", "deposit", "send"] }: { color?: string; caps?: Cap[] }) {
  const c = color;
  const [addr, setAddr] = useState("");
  const [sub, setSub] = useState<Cap>(caps[0]);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  const [bal, setBal] = useState<string | null>(null);
  const [pending, setPending] = useState<string | null>(null);
  const [a1, setA1] = useState(""); const [a2, setA2] = useState(""); const [to, setTo] = useState("");
  const [pair, setPair] = useState("EURC"); const [chain, setChain] = useState("Base");

  async function connect() { const p = getProvider(); if (!p) { setStatus("No EVM wallet (MetaMask / OKX)."); return; } await ensureArc(p); const x = await p.request({ method: "eth_requestAccounts" }); setAddr(x[0]); }
  async function loadBalance(x = addr) { if (!x) return; setBusy(true); setStatus(""); try { const { createUnifiedBalanceKitContext, getBalances } = await import("@circle-fin/unified-balance-kit"); const ctx = createUnifiedBalanceKitContext(); const res: any = await getBalances(ctx as any, { token: "USDC", sources: { address: x, chains: ["Arc_Testnet"] }, includePending: true } as any); setBal(res?.totalConfirmedBalance ?? "0"); setPending(res?.totalPendingBalance ?? null); setStatus(Number(res?.totalPendingBalance || 0) > 0 ? `$${res.totalPendingBalance} pending…` : "Balance loaded ✓"); } catch (e: any) { setStatus("Balance: " + (e?.shortMessage || e?.message || "unavailable")); } finally { setBusy(false); } }
  useEffect(() => { if (addr) loadBalance(addr); }, [addr]); // eslint-disable-line

  async function deposit() { if (!addr || !(Number(a1) > 0)) return; setBusy(true); setStatus("Depositing…"); try { const { createUnifiedBalanceKitContext, deposit: dep } = await import("@circle-fin/unified-balance-kit"); const ad = await adapterOf(getProvider()); const ctx = createUnifiedBalanceKitContext(); const r: any = await dep(ctx as any, { from: { adapter: ad, chain: "Arc_Testnet" }, token: "USDC", amount: a1 } as any); setStatus("Deposited ✓ " + (r?.txHash ? fmt(r.txHash) : "")); setA1(""); for (let i = 0; i < 6; i++) { await new Promise(r => setTimeout(r, 5000)); await loadBalance(); } } catch (e: any) { setStatus("Deposit failed: " + (e?.shortMessage || e?.message || "?")); } finally { setBusy(false); } }
  async function send() { if (!addr || !to || !(Number(a1) > 0)) return; setBusy(true); setStatus("Sending…"); try { const { createUnifiedBalanceKitContext, spend } = await import("@circle-fin/unified-balance-kit"); const ad = await adapterOf(getProvider()); const ctx = createUnifiedBalanceKitContext(); const r: any = await spend(ctx as any, { from: { adapter: ad }, to: { adapter: ad, chain: "Arc_Testnet", recipientAddress: to, useForwarder: false }, token: "USDC", amount: a1 } as any); setStatus("Sent ✓ " + (r?.txHash ? fmt(r.txHash) : "")); setTo(""); setA1(""); loadBalance(); } catch (e: any) { setStatus("Send failed: " + (e?.shortMessage || e?.message || "?")); } finally { setBusy(false); } }
  async function swap() { if (!addr || !(Number(a1) > 0)) return; setBusy(true); setStatus("Swapping…"); try { const { createSwapKitContext, swap: doSwap } = await import("@circle-fin/swap-kit"); const ad = await adapterOf(getProvider()); const ctx = createSwapKitContext(); const r: any = await doSwap(ctx as any, { from: { adapter: ad, chain: "Arc_Testnet" }, fromToken: "USDC", toToken: pair, amount: a1 } as any); setStatus("Swapped ✓ " + (r?.txHash ? fmt(r.txHash) : "")); setA1(""); } catch (e: any) { setStatus("Swap: " + (e?.shortMessage || e?.message || "needs KIT_KEY / liquidity")); } finally { setBusy(false); } }
  async function bridge() { if (!addr || !(Number(a1) > 0)) return; setBusy(true); setStatus("Bridging…"); try { const { BridgeKit } = await import("@circle-fin/bridge-kit"); const ad = await adapterOf(getProvider()); const kit: any = new (BridgeKit as any)(); const r: any = await kit.bridge({ from: { adapter: ad, chain: "Arc_Testnet" }, to: { chain }, token: "USDC", amount: a1 } as any); setStatus("Bridged ✓ " + (r?.txHash ? fmt(r.txHash) : "")); setA1(""); } catch (e: any) { setStatus("Bridge: " + (e?.shortMessage || e?.message || "unavailable on testnet")); } finally { setBusy(false); } }
  async function earn() { if (!addr || !(Number(a1) > 0)) return; setBusy(true); setStatus("Depositing to vault…"); try { const { createEarnKitContext, getVaults, deposit: vDep } = await import("@circle-fin/earn-kit"); const ad = await adapterOf(getProvider()); const ctx = createEarnKitContext(); let vaultId: any; try { const vs: any = await getVaults(ctx as any, { chain: "Arc_Testnet" } as any); vaultId = (vs?.vaults || vs)?.[0]?.id || (vs?.vaults || vs)?.[0]?.vaultId; } catch {} const r: any = await vDep(ctx as any, { from: { adapter: ad, chain: "Arc_Testnet" }, vault: vaultId, token: "USDC", amount: a1 } as any); setStatus("Earning ✓ " + (r?.txHash ? fmt(r.txHash) : "")); setA1(""); } catch (e: any) { setStatus("Earn: " + (e?.shortMessage || e?.message || "no vault on testnet")); } finally { setBusy(false); } }

  const label: Record<Cap, string> = { balance: "Balance", deposit: "Deposit", send: "Send", swap: "Swap", bridge: "Bridge", earn: "Earn" };
  const amtInput = (ph: string) => <div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 text-lg">$</span><input value={a1} onChange={e => setA1(e.target.value)} type="number" placeholder={ph} className={`w-full bg-gray-800 border border-gray-700 rounded-xl pl-8 pr-4 py-3 text-lg font-semibold focus:outline-none focus:border-${c}-500`} /></div>;
  const goBtn = (fn: () => void, txt: string) => <button onClick={fn} disabled={busy || !(Number(a1) > 0)} className={`w-full py-3 font-bold rounded-xl bg-${c}-500 text-black hover:opacity-90 disabled:opacity-40`}>{busy ? "…" : txt}</button>;

  return (
    <div className="space-y-4">
      <div className={`bg-${c}-500/10 border border-${c}-500/20 rounded-xl p-3 text-center text-xs text-${c}-300`}>⚡ Circle App Kit — {caps.map(x => label[x]).join(" · ")}</div>
      {!addr ? <button onClick={connect} className={`w-full py-3 font-bold rounded-xl bg-${c}-500 text-black hover:opacity-90`}>Connect for USDC</button> : <>
        {status && <div className="text-center text-xs text-gray-400">{status}</div>}
        {caps.length > 1 && <div className="flex gap-2 flex-wrap">{caps.map(s => <button key={s} onClick={() => setSub(s)} className={`flex-1 py-2 rounded-xl text-xs font-semibold ${sub === s ? `bg-${c}-500 text-black` : "bg-gray-800 text-gray-400"}`}>{label[s]}</button>)}</div>}
        {sub === "balance" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 text-center space-y-2"><div className="text-xs text-gray-500 uppercase tracking-wider">Unified USDC balance</div><div className={`text-4xl font-black text-${c}-300`}>{bal !== null ? `$${bal}` : "—"}</div>{pending && Number(pending) > 0 ? <div className="text-xs text-amber-400">⏳ ${pending} pending</div> : null}<button onClick={() => loadBalance()} disabled={busy} className="w-full py-2 bg-gray-800 border border-gray-700 rounded-xl text-xs font-semibold disabled:opacity-40">{busy ? "…" : "Refresh"}</button></div>}
        {sub === "deposit" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-3"><div className="text-xs text-gray-500">Move USDC from wallet into unified balance.</div>{amtInput("0.00")}{goBtn(deposit, "Deposit")}</div>}
        {sub === "send" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-3"><input value={to} onChange={e => setTo(e.target.value)} placeholder="0x… recipient" className={`w-full bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-sm font-mono focus:outline-none focus:border-${c}-500`} />{amtInput("0.00")}<button onClick={send} disabled={busy || !to || !(Number(a1) > 0)} className={`w-full py-3 font-bold rounded-xl bg-${c}-500 text-black hover:opacity-90 disabled:opacity-40`}>{busy ? "…" : "Send USDC"}</button></div>}
        {sub === "swap" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-3"><div className="flex items-center gap-2 text-sm"><span className="px-3 py-2 bg-gray-800 rounded-xl">USDC</span><span className="text-gray-500">→</span><select value={pair} onChange={e => setPair(e.target.value)} className="flex-1 bg-gray-800 border border-gray-700 rounded-xl px-3 py-2 text-sm focus:outline-none"><option>EURC</option><option>USDC</option></select></div>{amtInput("Amount to swap")}{goBtn(swap, `Swap USDC → ${pair}`)}<p className="text-[11px] text-gray-600 text-center">Swap via Circle App Kit (may require a KIT_KEY).</p></div>}
        {sub === "bridge" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-3"><div className="flex items-center gap-2 text-sm"><span className="px-3 py-2 bg-gray-800 rounded-xl">Arc</span><span className="text-gray-500">→</span><select value={chain} onChange={e => setChain(e.target.value)} className="flex-1 bg-gray-800 border border-gray-700 rounded-xl px-3 py-2 text-sm focus:outline-none"><option>Base</option><option>Ethereum</option><option>Avalanche</option><option>Arbitrum</option></select></div>{amtInput("Amount to bridge")}{goBtn(bridge, `Bridge to ${chain}`)}<p className="text-[11px] text-gray-600 text-center">Cross-chain USDC via CCTP.</p></div>}
        {sub === "earn" && <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-3"><div className="text-xs text-gray-500">Deposit USDC into a yield vault.</div>{amtInput("0.00")}{goBtn(earn, "Deposit to earn")}<p className="text-[11px] text-gray-600 text-center">Earn yield via Circle App Kit vaults.</p></div>}
      </>}
    </div>
  );
}
